packages:
  - www
  - packages/*
  - configs/*
  - templates/*

catalog:
  '@eslint/js': ^9.34.0
  '@types/node': ^24.3.0
  eslint: ^9.34.0
  typescript: 5.9.2

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - lefthook
  - sharp
