packages:
  - www
  - packages/*
  - configs/*
  - templates/*

catalog:
  '@eslint/js': ^9.37.0
  '@types/node': ^24.7.1
  eslint: ^9.37.0
  typescript: 5.9.3

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - lefthook
  - sharp
